### ISSUE TITLE
When linking plex account, using plex.com but should be plex.tv (should be plex.tv/link)

### ISSUE THREAD

**Issue by ispaydeu** [mjrode/WhatToWatch#19]
This issue is occurring as  of 4/20/2019:

After associating your google credentials with the service then it tries to have you link your plex account. On that page it has the incorrect URL of "Enter the code below to link your account on  plex.com/link" but it should be using plex.tv/link 

![Screen Shot 2019-04-20 at 6 51 19 AM](https://user-images.githubusercontent.com/31388982/56456419-2d410680-633a-11e9-8ebb-197d66a17331.png)

**Comment by mjrode** [comment]
The link was correct but the title was misleading. The link text has been changed to *Link Plex Account* which points to `https://plex.tv/link`
